server:
  port: 8082
  servlet:
    context-path: /hdr-civ

project:
  version: V5.0
  name: hdr-civ

swagger:
  ctrlName: com.goodwill
  title: hdr-civ-v5
  description: hdr-civ-v5
  version: 5.0
  url: "http://www.goodwill.com/"

management:
  endpoints:
    web:
      exposure:
        include: '*'
#spring:
#  datasource:
#    url: jdbc:mysql://192.168.2.202:3306/hdr-civ-v5?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: hduap001
#    driver-class-name: com.mysql.jdbc.Driver
