server:
  port: 8182
spring:
  application:
    name: rest-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.202:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'