server:
  port: 8082
spring:
  application:
    name: civ
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.202:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'